Feature/Authentication
GwenDiky/AuthMicroservice pull request #2
Opened 2024-10-09 15:39 UTC by GwenDiky

2024-10-10 12:57 UTC, ChainHokesss requested changes
Пока так, посмотрел не все, сначала поправь комментарии эти, попробуй найти либу, которая реализует авторизацию по токену, и интегрируй ее сюда, не нужно изобретать велосипед
не везде стоят тайпинги
не понимаю архитектуру приложения, можешь объяснить, что для чего используется

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    USER = "user"
auth сервис не должен знать про роли, тк если ты захочешь интегрировать auth сервис с другим сервисом, где роли будут другие, будут проблемы

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/security/config.py
> +from ..database.postgres_repo import UserRepository
это не очень хорошая практика (такие иморты)

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/security/config.py
> +DB_NAME = os.getenv("DB_NAME")
для хранения конфигов используют pydantic_settings.BaseSettings
он умеет автоматически парсить env

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    return date.today()
где это используется ?

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    id: UUID = Field(default_factory=uuid4)  # generate automatic
убери комментарии

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    email: EmailStr | None = None
email не обязательный? почему решила так делать ?

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    email: Optional[EmailStr] = None
старайся везде писать в одном формате. если  type | None, то уже Optional не используй

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    password: bytes
почему password: bytes ?

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +    is_active: bool = True
я могу создать не активного юзера ?

2024-10-10 12:57 UTC, ChainHokesss commented on auth/main.py
очень странно, что точка входа в приложение лежит внутри auth, условно если у тебя появится auth_v2, что будешь делать в таком случае ?

лучше создай папку src где будут лежать main.py config.py auth infrastructure
еще заметил, что папка называется  infrastrаcture

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/Dockerfile
> +CMD ["uvicorn", "auth.main:app", "--host", "0.0.0.0", "--port", "8083", "--reload"]
пусть контейнер запускается из компоуза, тк может быть ситуация когда ты захочешь запустить 2 инстанса своего приложения с разной конфигурацией запуска приложения (например на разных портах)

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
не понимаю почему api лежит в infrastructure

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
> +from ..exceptions import (
-

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
> +from ..security.config import user_repo, setup_logging
-

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/utils/utils_jwt.py
почему utils внутри api ?

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/database/models/user.py
> +        }
этой логикой не должна заниматься модель, такая логика уже есть в pydantic

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/database/postgres_repo.py
> +class UserRepository:
почему UserRep лежит в postgres_repo.py?

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/database/postgres_repo.py
> +        self.db_url = os.getenv("SQLALCHEMY_DATABASE_URL")
это оно должно доставать из конфига а не напрямую из env

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/database/postgres_repo.py
> +        )
странно, почему у тебя репозиторий создает конекшен к бд, но ты его дополнительно прокидываешь в ручку, разбей это, репозиторий не должен этим заниматься

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/database/postgres_repo.py
> +                    return "user wasn't found. check up your statement again"
почему ты отдаешь строку ?

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/database/postgres_repo.py
> +                    return "user wasn't found. check up your statement again"
выше

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
> +    return {"message": "User created", "user": new_user}
эта логика должна быть в репозитории

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
> +    )
User(**(user.model_dump() | {доп поля, которых нет в UserCreate}))

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
> +    return user
это не должно здесь лежать

2024-10-10 12:57 UTC, ChainHokesss commented on auth/domain/entities/user.py
> +class UserCreate(BaseModel):
UserCreateSchema

2024-10-10 12:57 UTC, ChainHokesss commented on infrastracture/api/user_routers.py
> +        user: UserSchema = Depends(validate_auth_user_login),
странно выглядит, это не должен быть depends, на вход поступает схема ее ты валидируешь и получешь из нее user, а из user токен

2024-10-14 10:45 UTC, GwenDiky commented on infrastracture/database/postgres_repo.py
> +        )
ручку?

2024-10-15 11:22 UTC, ChainHokesss requested changes
вынеси логику из ручек в сервисы

2024-10-15 11:22 UTC, ChainHokesss commented on requirements.txt
зачем тебе requirements.txt?

2024-10-15 11:22 UTC, ChainHokesss commented on exceptions.py
этот файл должен лежать в auth папку

2024-10-15 11:22 UTC, ChainHokesss commented on docker-compose.yml
сделай папку tests на уровне папки auth туда положи тесты + conftest.py

2024-10-15 11:22 UTC, ChainHokesss commented on auth/api/main.py
Почему main.py лежит в api ? вынеси его в папку auth

2024-10-15 11:22 UTC, ChainHokesss commented on auth/api/dependecies.py
> +    return user
не используется

2024-10-15 11:22 UTC, ChainHokesss commented on auth/api/dependecies.py
> +    #         )
не используется

2024-10-15 11:22 UTC, ChainHokesss commented on auth/api/routers/user_routers.py
> +        raise HTTPException(status_code=500, detail="Internal Server Error")
не очень хорошая практика except Exception

2024-10-15 11:49 UTC, GwenDiky commented on requirements.txt
для того чтобы в будущем настроить ci/cd, без обращения к файлам poetry, которые могут обрабатываться некорректно

2024-10-15 11:50 UTC, GwenDiky commented on auth/api/dependecies.py
> +    #         )
это я в будущем планирую использовать. увидела реализацию пермишинов и добавила в проект в виде комментариев

2024-10-21 10:01 UTC, ChainHokesss requested changes

2024-10-21 10:01 UTC, ChainHokesss commented on auth/services/handlers/user.py
перенеси папку handlers в api

2024-10-21 10:01 UTC, ChainHokesss commented on auth/database/repo.py
> +        return user
почему у тебя базовый репозиторий зависит от модели юзер? Если вдруг в этом сервисе появиться еще одна модель, то как ты будешь наследовать новый репозиторий от этого ?

2024-10-21 10:01 UTC, ChainHokesss commented on auth/database/user.py
> +        return result.scalars().first()
тут этого не должно быть

2024-10-21 10:01 UTC, ChainHokesss commented on auth/database/user.py
> +        return result.scalars().first()
твоя модель не должна хранить логику

2024-10-22 08:39 UTC, ChainHokesss requested changes
Мне не очень хочется, чтобы ты использовала ddd (clean arc) на этом проекте, так как, чисто по моему мнению, это очень сильно замедляет разработку, а нормальные гайды по ddd тяжело найти

2024-10-22 08:39 UTC, ChainHokesss commented on auth/database/user.py
> +    role = Column("role", String, nullable=False, default="user")
auth  не должен знать про role, так как ты не сможешь подрудить новый сервис где будут уже другие роли

2024-10-22 08:39 UTC, ChainHokesss commented on auth/database/user.py
> +    role = Column("role", String, nullable=False, default="user")
а 3яя система вообще может не иметь ролей, а использовать  iam, если ты хотела с помощью этого параметра определять админа для системы, то просто используй is_superuser, а это уже может храниться в модели пользователя

2024-10-22 08:39 UTC, ChainHokesss commented on auth/core/base.py
это нужно ?

2024-10-22 08:39 UTC, ChainHokesss commented on auth/core/settings.py
почему бы не объединить settings и config?

2024-10-22 08:39 UTC, ChainHokesss commented on auth/core/utils/utils_users.py
> +        new_token = await auth_utils.encode_jwt(user.to_dict())
разве у модели юзера есть метод to_dict?

2024-10-22 08:39 UTC, ChainHokesss commented on auth/core/utils/utils_users.py
> +        new_token = await auth_utils.encode_jwt(user.to_dict())
не оборачивай весь код в try except, это выглядит не супер красиво, оберни только ту функцию, котороая потенциально может вызвать ошибку, в этом случае это auth_utils.encode_jwt

2024-10-22 08:39 UTC, ChainHokesss commented on auth/core/utils/utils_jwt.py
> +        expire = now + timedelta(minutes=expire)
не понимаю зачем оно принимает expire_timedelta и expire, может оно будет принимать либо то либо то, короче не самое красивое решение

2024-10-22 08:39 UTC, ChainHokesss commented on auth/database/repo.py
> +            raise BadRequestException(f"Database error: {db_error}")
почему базовый репозиторий использует функции, зависящие от полей, которые могут не быть в дочерних репозиториях (что произойдет, если мы создадим репозиторий проекта, наследуемся от SqlAlchemyRepository, и вызовем жту функцию ?)

2024-10-22 08:39 UTC, ChainHokesss commented on auth/database/repo.py
> +        return user
выше

2024-10-22 08:39 UTC, ChainHokesss commented on auth/database/repo.py
> +        return model
опять current user  тут

2024-10-22 10:34 UTC, ChainHokesss approved these changes

2024-10-22 10:34 UTC, ChainHokesss commented on auth/core/config.py
> +load_dotenv()
зачем ты подгружаешь переменные, если BaseSettings сам это делает

2024-10-22 10:34 UTC, ChainHokesss commented on auth/schemas/user.py
> +    role: str = "user"
тут тогда тоже

2024-10-22 10:34 UTC, ChainHokesss commented on auth/schemas/user.py
> +    role: str
 и тут

2024-10-23 10:20 UTC, merged