Feature/email
GwenDiky/AuthMicroservice pull request #5
Opened 2024-10-17 17:52 UTC by GwenDiky

2024-11-06 14:20 UTC, ChainHokesss requested changes
пока так, пересмотри все, потом пингуй, когда поправишь
Поищи в гите примеры хорошего кода на фаст апи

2024-11-06 14:20 UTC, ChainHokesss commented on requirements.txt
попробуй убрать requirements.txt и поменять логику сборки используя pyproject.toml

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +                 db: AsyncSession = Depends(get_async_session)) \
почему тут '\'

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
>      new_user = User(**user_data)
если ты тут сделаешь user.password = hashed_password оно сломается ?
если нет, тогда не понимаю зачем делать дикт и все равно обращаться по названию атрибута, а преобразовывать в дикт можно уже в User(**user.model_dump())

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +            result.date_of_birth = result.date_of_birth.date()
уже плохо, что у тебя date_of_birth может быть и datetime и date, придется так во всех местах обрабатывать

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    return {"message": "Verification email resent successfully"}
сделай другой тип для таких респонсов, тк в твоем случае фронт не будет знать схему ответа, а это плохо (потому что некоторые фреймворки фронта генерят сервисы на основе свагера)

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +        raise Exception("Recipient email is not verified. Please verify the email first.")
почему бы не райзить кастомную ошибку, которую может фреймворк перехватывать

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +                           ) \
\ ?

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +                 redis_client=Depends(get_redis)) -> dict:
посмотри  pep 8   как там переносы делаются, у тебя сейчас не по pep8

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    return {"message": "Successfully logged out"}
написал выше

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    token_data = await decode_url_safe_token(token)
пусть decode_url_safe_token возвращает пайдентик

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +@user_router.get('/reset-password/verify/{token}/{new_password}')
почему password в урле ?? это не секьюрно

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    }
должно возвращать pydantic

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +@user_router.get("/get-all-users", response_model=ResponseSchema, response_model_exclude_none=True)
не по ресту название

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +        limit: int = 10,
вынеси в отдельный объект это, тк будет переиспользоваться, объект должен уметь принимать query и применять к нему пагинацию

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +            ))
в таких кейсах используется list compr. так красивее и лучше читается

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    result = await UserRepository(db).get_all_users(page, limit, sort, filter)
get_all_users - должна отдавать уже список пользователей, а не каждый раз преобразовывать  result при использовании

2024-11-06 14:20 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    return ResponseSchema(
почему название ResponseSchema? как фронт поймет какие данные он получит? если ты не описываешь их, а просто возвращаешь дикт, зачем у успешного ответа detail?

2024-11-06 14:20 UTC, ChainHokesss commented on auth/core/config.py
> +    aws_secret_access_key:str = Field(validation_alias="AWS_SECRET_ACCESS_KEY")
ты не должна описывать названия в верхнем регистре BaseSettings сам понимает

2024-11-06 15:36 UTC, GwenDiky commented on auth/api/handlers/user.py
> +                 db: AsyncSession = Depends(get_async_session)) \
что тут? пробел? если да, то убрала

2024-11-15 14:04 UTC, ChainHokesss approved these changes

2024-11-15 14:04 UTC, ChainHokesss commented on auth/api/handlers/user.py
очень много импортов, надо что-то сделать с этим

2024-11-15 14:04 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    email = user.email
зачем нужна эта строчка

2024-11-15 14:04 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    total_records = await UserRepository(db).get_total_count()
эту логику можно вынести в сервис, чтобы он все отдавал и каунт

2024-11-17 09:18 UTC, GwenDiky commented on auth/api/handlers/user.py
может вывести импорты связанные с utils вынести в отдельный файл?

2024-11-18 09:33 UTC, GwenDiky commented on auth/api/handlers/user.py
> +    total_records = await UserRepository(db).get_total_count()
по сути у меня же и так эта логика в сервисах? в роутере только вызываю

2024-11-18 11:38 UTC, ChainHokesss commented on auth/api/handlers/user.py
нет, просто можно не импортировать все функции, а импортить модули, а оттуда использовать функции

2024-11-18 11:39 UTC, ChainHokesss commented on auth/api/handlers/user.py
> +    total_records = await UserRepository(db).get_total_count()
смотри, есть сервисы, а есть репозитории, репозитории инкапсулируют в себе логику взаимодействия с базой, а сервисы используют репозитории для бизнес логики

2024-11-18 14:39 UTC, merged